@echo off
REM Generated by Agent Pack launcher. Do not edit by hand.
setlocal
set "PROJECT_DIR=%~dp0"
set "LOCK=%PROJECT_DIR%\.agents\agent-pack.lock.json"
set "BINDING=%PROJECT_DIR%\.agents\agent-pack.local.json"
set "PACK_DIR="
if defined AGENT_PACK_DIR set "PACK_DIR=%AGENT_PACK_DIR%"
if "%~1"=="bind" if "%~2"=="--pack" if not "%~3"=="" set "PACK_DIR=%~3"
if "%~1"=="migrate" if "%~2"=="--pack" if not "%~3"=="" set "PACK_DIR=%~3"
if not defined PACK_DIR for /f "delims=" %%i in ('python -c "import json, os, sys; p=sys.argv[1]; print(json.load(open(p, encoding='utf-8')).get('packPath','') if os.path.exists(p) else '')" "%BINDING%" 2^>NUL') do set "PACK_DIR=%%i"
if not defined PACK_DIR for /f "delims=" %%i in ('py -3 -c "import json, os, sys; p=sys.argv[1]; print(json.load(open(p, encoding='utf-8')).get('packPath','') if os.path.exists(p) else '')" "%BINDING%" 2^>NUL') do set "PACK_DIR=%%i"
if not defined PACK_DIR for /f "delims=" %%i in ('python3 -c "import json, os, sys; p=sys.argv[1]; print(json.load(open(p, encoding='utf-8')).get('packPath','') if os.path.exists(p) else '')" "%BINDING%" 2^>NUL') do set "PACK_DIR=%%i"
if not defined PACK_DIR for /f "delims=" %%i in ('python -c "import json, os, sys; p=sys.argv[1]; print(json.load(open(p, encoding='utf-8')).get('packPath','') if os.path.exists(p) else '')" "%LOCK%" 2^>NUL') do set "PACK_DIR=%%i"
if not defined PACK_DIR for /f "delims=" %%i in ('py -3 -c "import json, os, sys; p=sys.argv[1]; print(json.load(open(p, encoding='utf-8')).get('packPath','') if os.path.exists(p) else '')" "%LOCK%" 2^>NUL') do set "PACK_DIR=%%i"
if not defined PACK_DIR for /f "delims=" %%i in ('python3 -c "import json, os, sys; p=sys.argv[1]; print(json.load(open(p, encoding='utf-8')).get('packPath','') if os.path.exists(p) else '')" "%LOCK%" 2^>NUL') do set "PACK_DIR=%%i"
if defined PACK_DIR goto pack_resolved
if exist "%LOCK%" (
  echo Error: project is installed, but Agent Pack is not bound on this machine. Run X:\path\to\agent-pack\agent-pack.cmd bind. 1>&2
  exit /b 1
)
echo Error: missing .agents/agent-pack.lock.json; run install first. 1>&2
exit /b 1
:pack_resolved
if exist "%PACK_DIR%\agent-pack.cmd" goto pack_valid
echo Error: invalid local Agent Pack path: %PACK_DIR%. Run bind again. 1>&2
exit /b 1
:pack_valid
cd /d "%PROJECT_DIR%"
call "%PACK_DIR%\agent-pack.cmd" %*
exit /b %errorlevel%
