# Generated by Agent Pack launcher. Do not edit by hand.
$ErrorActionPreference = "Stop"
$projectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$lock = Join-Path $projectDir ".agents/agent-pack.lock.json"

function Read-PackDir {
  param([string] $LockPath)
  if (-not (Test-Path -LiteralPath $LockPath)) { return "" }
  try {
    $data = Get-Content -Raw -LiteralPath $LockPath | ConvertFrom-Json
    if ($data.packPath) { return [string] $data.packPath }
  } catch {
    return ""
  }
  return ""
}

if ($args.Count -ge 3 -and $args[0] -eq "migrate" -and $args[1] -eq "--pack") { $packDir = $args[2] }
else { $packDir = Read-PackDir $lock }
if (-not $packDir) { Write-Error "Error: missing .agents/agent-pack.lock.json; cannot locate Agent Pack."; exit 1 }
Set-Location $projectDir
& (Join-Path $packDir "agent-pack.ps1") @args
exit $LASTEXITCODE
