"""兼容旧导入的发布合同 facade；实现按 preview、promotion、build 职责拆分。"""

from release_build_contract import validate_registry_plan, validate_release_build
from release_contract_support import (
    BUILD_SCHEMA,
    BUMPS,
    EMPTY_SHA256,
    GIT_OBJECT_ID,
    PREVIEW_SCHEMA,
    PROMOTION_PLAN_SCHEMA,
    PROMOTION_SCHEMA,
    PSR_VERSION,
    REGISTRY_PLAN_SCHEMA,
    RELEASE_ARTIFACT_KINDS,
    SECRET_PATTERNS,
    SEMVER,
    SHA256,
    URL_USERINFO_PATTERN,
    UV_VERSION,
    ReleaseContractError,
    approval_sha256,
    artifact_record,
    canonical_json_bytes,
    endpoint_sha256,
    read_json,
    redact,
    release_artifacts,
    require_approval_digest,
    required_psr_executable,
    required_uv_executable,
    run_git,
    sha256_bytes,
    sha256_file,
    source_identity,
    urlopen_no_redirect,
    write_json,
)
from release_preview_contract import resolve_artifact, validate_preview, verify_artifacts
from release_promotion_contract import validate_promotion, validate_promotion_plan

__all__ = [
    "BUILD_SCHEMA",
    "BUMPS",
    "EMPTY_SHA256",
    "GIT_OBJECT_ID",
    "PREVIEW_SCHEMA",
    "PROMOTION_PLAN_SCHEMA",
    "PROMOTION_SCHEMA",
    "PSR_VERSION",
    "REGISTRY_PLAN_SCHEMA",
    "RELEASE_ARTIFACT_KINDS",
    "SECRET_PATTERNS",
    "SEMVER",
    "SHA256",
    "URL_USERINFO_PATTERN",
    "UV_VERSION",
    "ReleaseContractError",
    "approval_sha256",
    "artifact_record",
    "canonical_json_bytes",
    "endpoint_sha256",
    "read_json",
    "redact",
    "release_artifacts",
    "require_approval_digest",
    "required_psr_executable",
    "required_uv_executable",
    "resolve_artifact",
    "run_git",
    "sha256_bytes",
    "sha256_file",
    "source_identity",
    "urlopen_no_redirect",
    "validate_preview",
    "validate_promotion",
    "validate_promotion_plan",
    "validate_registry_plan",
    "validate_release_build",
    "verify_artifacts",
    "write_json",
]
